import type { Metadata } from "next";
import Header from "@/components/header/header";

export const metadata: Metadata = {
  title: "Nosso TBR",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />

      <div className="pt-24 p-6 flex flex-col items-center gap-6">
        {children}
      </div>
    </>
  );
}
